language: php

php: 7.2

before_install:
- composer global require hirak/prestissimo

install:
- composer install
- nvm install 10
- npm install --global grunt-cli
- npm install

script:
- grunt

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
