<?php namespace Redaxscript\Template; ?>

<!-- base -->

<?php echo Tag::base(); ?>

<!-- title -->

<?php echo Tag::title(Helper::getRegistry('fullRoute') ? Helper::getTitle() : Helper::getSetting('title')); ?>

<!-- meta -->

<?php echo Tag::meta()
	->init()
	->append('charset', Helper::getSetting('charset'))
	->append(['name' => 'author', 'content' => Helper::getSetting('author')])
	->append(['name' => 'generator', 'content' => Helper::getLanguage('name', '_package') . ' ' . Helper::getLanguage('version', '_package')])
	->append(['name' => 'description', 'content' => Helper::getRegistry('fullRoute') ? Helper::getDescription() : Helper::getSetting('description')])
	->append(['name' => 'keywords', 'content' => Helper::getRegistry('fullRoute') ? Helper::getKeywords() : Helper::getSetting('keywords')])
	->append(['name' => 'robots', 'content' => Helper::getRegistry('fullRoute') ? Helper::getRobots() : 'all'])
	->append(['name' => 'viewport', 'content' => 'width=device-width'])
	->append(['name' => 'theme-color', 'content' => '#323e4c'])
	->append(['name' => 'msapplication-navbutton-color', 'content' => '#323e4c'])
	->append(['name' => 'apple-mobile-web-app-status-bar-stylecontent', 'content' => '#323e4c'])
	->append(['name' => 'msvalidate.01', 'content' => '9904AD2FB469A0860172008547D3BD27'])
	->append(['name' => 'google-site-verification', 'content' => 'Wz0d7aVxf_6sQ54_ttyu2sMrw-yJLBXd6h4HknDNYaI']); ?>

<!-- link -->

<?php echo Tag::link()
	->init()
	->append(['href' => Helper::getRegistry('fullRoute') ? Helper::getCanonical() : Helper::getRegistry('root'), 'rel' => 'canonical'])
	->append(['href' => 'templates/default/assets/images/favicon.ico', 'rel' => 'shortcut icon'])
	->append(['href' => 'templates/default/assets/images/favicon.png', 'rel' => 'apple-touch-icon'])
	->appendFile(
	[
		'https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&amp;subset=' . Helper::getSubset(),
		'https://fonts.googleapis.com/css?family=Pacifico&amp;text=What+are+you?;subset=' . Helper::getSubset(),
		'templates/redaxscript/dist/styles/redaxscript.min.css'
	])
	->rewrite(
	[
		'../../../../templates' => '../../templates',
		'../../../../modules' => '../../modules'
	])
	->concat(); ?>

<?php echo Tag::link()->init('admin'); ?>

<!-- head script -->

<?php echo Tag::script()
	->init('head')
	->prependFile('assets/scripts/init.js')
	->transportVar('rs', Helper::getTransport())
	->concat(); ?>
