<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'admin/head.phtml',
			'default/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<?php if (!Helper::getRegistry('fullRoute')): ?>
		<body class="rs-body-homepage">
	<?php else: ?>
		<body class="rs-body">
	<?php endif; ?>
		<?php $body = Tag::partial(
		[
			Helper::getRegistry('fullRoute') ? 'redaxscript/header.phtml' : null,
			'redaxscript/main.phtml',
			Helper::getRegistry('fullRoute') ? 'default/footer.phtml' : null,
			'admin/script.phtml',
			'default/script.phtml'
		]); ?>
		<?php echo Tag::partial(
		[
			'admin/panel.phtml',
			'default/menu-status.phtml'
		]); ?>
		<div class="rs-has-menu">
			<?php echo $body; ?>
		</div>
	</body>
</html>
