<?php namespace Redaxscript\Template; ?>

<!DOCTYPE html>
<html lang="<?php echo Helper::getRegistry('language'); ?>" dir="<?php echo Helper::getDirection(); ?>" class="<?php echo Helper::getClass('rs-is-'); ?>">

	<!-- head -->

	<head>
		<?php echo Tag::partial(
		[
			'admin/head.phtml',
			'redaxscript/head.phtml'
		]); ?>
	</head>

	<!-- body -->

	<?php if (Helper::getRegistry('fullRoute')): ?>
		<body class="rs-body">
			<?php $body = Tag::partial(
			[
				'redaxscript/header.phtml',
				'redaxscript/main.phtml',
				'default/footer.phtml',
				'admin/script.phtml',
				'default/script.phtml'
			]); ?>
			<?php echo Tag::partial(
			[
				'admin/panel.phtml',
				'admin/dashboard.phtml',
				'default/menu-status.phtml'
			]); ?>
			<div class="rs-has-menu">
				<?php echo $body; ?>
			</div>
		</body>
	<?php else: ?>
		<body class="rs-body-homepage">
			<?php $body = Tag::partial(
			[
				'redaxscript/main.phtml',
				'admin/script.phtml',
				'default/script.phtml'
			]); ?>
			<?php echo Tag::partial(
			[
				'admin/panel.phtml',
				'admin/dashboard.phtml'
			]); ?>
			<?php echo $body; ?>
		</body>
	<?php endif; ?>
</html>
