<?php namespace Redaxscript\Template; ?>

<!-- homepage -->

<?php if (!Tag::getRegistry('fullRoute')): ?>
	<main class="rs-fn-clearfix">
		<?php echo Tag::partial('redaxscript/homepage.phtml'); ?>
	</main>

<!-- else default -->

<?php else: ?>
	<main id="main" class="rs-main rs-fn-clearfix">

		<!-- error -->

		<?php if (Tag::getRegistry('contentError')): ?>
			<div class="rs-wrapper rs-wrapper-page rs-fn-clearfix">
				<?php echo Tag::partial('default/error.phtml'); ?>
			</div>

		<!-- else content and sidebar -->

		<?php elseif (Tag::getRegistry('firstParameter') === 'api' || Tag::getRegistry('firstParameter') === 'documentation'): ?>
			<div class="rs-wrapper rs-wrapper-page rs-has-sidebar rs-fn-clearfix">
				<?php echo Tag::partial(
				[
					'default/content.phtml',
					'redaxscript/sidebar.phtml'
				]); ?>
			</div>

		<!-- else content -->

		<?php else: ?>
			<div class="rs-wrapper rs-wrapper-page rs-fn-clearfix">
				<?php echo Tag::partial('default/content.phtml'); ?>
			</div>
		<?php endif; ?>
	</main>
<?php endif; ?>