<?php namespace Redaxscript\Template; ?>

<!-- homepage -->

<?php if (!Helper::getRegistry('fullRoute')): ?>
	<main>
		<?php echo Tag::partial('redaxscript/homepage.phtml'); ?>
	</main>

<!-- else default -->

<?php else: ?>
	<main id="main" class="rs-main">

		<!-- bad response -->

		<?php if (Helper::getResponseCode() === 404): ?>
			<div class="rs-wrapper rs-wrapper-page">
				<?php echo Tag::partial('default/error.phtml'); ?>
			</div>

		<!-- else content and sidebar -->

		<?php elseif (Helper::getRegistry('firstParameter') === 'api' || Helper::getRegistry('firstParameter') === 'documentation'): ?>
			<div class="rs-wrapper rs-wrapper-page rs-has-sidebar">
				<?php echo Tag::partial(
				[
					'default/content.phtml',
					'redaxscript/sidebar.phtml'
				]); ?>
			</div>

		<!-- else content -->

		<?php else: ?>
			<div class="rs-wrapper rs-wrapper-page">
				<?php echo Tag::partial('default/content.phtml'); ?>
			</div>
		<?php endif; ?>
	</main>
<?php endif; ?>
