<?php namespace Redaxscript\Template; ?>

<!-- logic -->

<label class="rs-fn-toggle-menu rs-label-toggle-menu" for="status-menu">Menu</label>
<label class="rs-fn-close-menu rs-label-close-menu" for="status-menu"></label>

<!-- list -->

<ul class="rs-fn-dropdown rs-fn-menu rs-list-menu">
	<li>
		<a href="<?php echo Helper::getRegistry('rewriteRoute'); ?>download">Download</a>
	</li><!--
	--><li>
		<a href="<?php echo Helper::getRegistry('rewriteRoute'); ?>documentation">Documentation</a>
	</li><!--
	--><li>
		<a href="<?php echo Helper::getRegistry('rewriteRoute'); ?>features">Features</a>
	</li><!--
	--><li>
		<a href="<?php echo Helper::getRegistry('rewriteRoute'); ?>api">API</a>
	</li>
</ul>
