<?php namespace Redaxscript\Template; ?>

<aside id="sidebar" class="rs-sidebar">
	<?php echo Tag::searchForm(); ?>

	<!-- navigation -->

	<?php if(Tag::getRegistry('firstParameter') === 'api' || Tag::getRegistry('firstParameter') === 'documentation'): ?>
		<?php include('templates/redaxscript/helper/' . Tag::getRegistry('firstParameter') . '.php'); ?>
		<?php include('templates/redaxscript/navigation.phtml'); ?>
	<?php endif; ?>
</aside>
